[general]
# Disable screensaver and power management while playing
inhibit_screensaver=1

[filter]
# Any process matched by these names will automatically trigger gamemode
# without needing the user to launch it explicitly with `gamemoderun`
SUPERHOT=1
cs2=1
dota2=1
Cyberpunk2077=1
eldenring=1
hl2=1
starfield=1

[cpu]
# Lock the CPU governor to maximum performance, avoiding power-saving drop-outs
pin_cores=0
park_cores=0
governor=performance
governor_default=schedutil

[gpu]
# By default, GameMode will try to use the most aggressive clock states
nv_powermizer_mode=1
amd_performance_level=high

[custom]
# You can execute shell commands when games start (e.g., clear memory caches)
# start=
# end=
